// Generated by view binder compiler. Do not edit!
package com.son.lecture_project.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.ScrollView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.recyclerview.widget.RecyclerView;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.son.lecture_project.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityHomeBinding implements ViewBinding {
  @NonNull
  private final ScrollView rootView;

  @NonNull
  public final Button btnStartTimer;

  @NonNull
  public final RecyclerView recyclerNotices;

  @NonNull
  public final RecyclerView recyclerSchedule;

  @NonNull
  public final TextView tvDate;

  @NonNull
  public final TextView tvTimer;

  private ActivityHomeBinding(@NonNull ScrollView rootView, @NonNull Button btnStartTimer,
      @NonNull RecyclerView recyclerNotices, @NonNull RecyclerView recyclerSchedule,
      @NonNull TextView tvDate, @NonNull TextView tvTimer) {
    this.rootView = rootView;
    this.btnStartTimer = btnStartTimer;
    this.recyclerNotices = recyclerNotices;
    this.recyclerSchedule = recyclerSchedule;
    this.tvDate = tvDate;
    this.tvTimer = tvTimer;
  }

  @Override
  @NonNull
  public ScrollView getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityHomeBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityHomeBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_home, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityHomeBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.btnStartTimer;
      Button btnStartTimer = ViewBindings.findChildViewById(rootView, id);
      if (btnStartTimer == null) {
        break missingId;
      }

      id = R.id.recyclerNotices;
      RecyclerView recyclerNotices = ViewBindings.findChildViewById(rootView, id);
      if (recyclerNotices == null) {
        break missingId;
      }

      id = R.id.recyclerSchedule;
      RecyclerView recyclerSchedule = ViewBindings.findChildViewById(rootView, id);
      if (recyclerSchedule == null) {
        break missingId;
      }

      id = R.id.tvDate;
      TextView tvDate = ViewBindings.findChildViewById(rootView, id);
      if (tvDate == null) {
        break missingId;
      }

      id = R.id.tvTimer;
      TextView tvTimer = ViewBindings.findChildViewById(rootView, id);
      if (tvTimer == null) {
        break missingId;
      }

      return new ActivityHomeBinding((ScrollView) rootView, btnStartTimer, recyclerNotices,
          recyclerSchedule, tvDate, tvTimer);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
