// Generated by view binder compiler. Do not edit!
package com.son.lecture_project.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.LinearLayout;
import android.widget.NumberPicker;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.son.lecture_project.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityTimerBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final Button btnStartTimer;

  @NonNull
  public final NumberPicker npTimer;

  private ActivityTimerBinding(@NonNull LinearLayout rootView, @NonNull Button btnStartTimer,
      @NonNull NumberPicker npTimer) {
    this.rootView = rootView;
    this.btnStartTimer = btnStartTimer;
    this.npTimer = npTimer;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityTimerBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityTimerBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_timer, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityTimerBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.btn_start_timer;
      Button btnStartTimer = ViewBindings.findChildViewById(rootView, id);
      if (btnStartTimer == null) {
        break missingId;
      }

      id = R.id.np_timer;
      NumberPicker npTimer = ViewBindings.findChildViewById(rootView, id);
      if (npTimer == null) {
        break missingId;
      }

      return new ActivityTimerBinding((LinearLayout) rootView, btnStartTimer, npTimer);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
