// Generated by view binder compiler. Do not edit!
package com.son.lecture_project.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ScrollView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.son.lecture_project.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivitySignupBinding implements ViewBinding {
  @NonNull
  private final ScrollView rootView;

  @NonNull
  public final Button btnSendCode;

  @NonNull
  public final Button btnSignupConfirm;

  @NonNull
  public final EditText editSignupEmail;

  @NonNull
  public final EditText editSignupName;

  @NonNull
  public final EditText editSignupPassword;

  private ActivitySignupBinding(@NonNull ScrollView rootView, @NonNull Button btnSendCode,
      @NonNull Button btnSignupConfirm, @NonNull EditText editSignupEmail,
      @NonNull EditText editSignupName, @NonNull EditText editSignupPassword) {
    this.rootView = rootView;
    this.btnSendCode = btnSendCode;
    this.btnSignupConfirm = btnSignupConfirm;
    this.editSignupEmail = editSignupEmail;
    this.editSignupName = editSignupName;
    this.editSignupPassword = editSignupPassword;
  }

  @Override
  @NonNull
  public ScrollView getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivitySignupBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivitySignupBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_signup, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivitySignupBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.btnSendCode;
      Button btnSendCode = ViewBindings.findChildViewById(rootView, id);
      if (btnSendCode == null) {
        break missingId;
      }

      id = R.id.btnSignupConfirm;
      Button btnSignupConfirm = ViewBindings.findChildViewById(rootView, id);
      if (btnSignupConfirm == null) {
        break missingId;
      }

      id = R.id.editSignupEmail;
      EditText editSignupEmail = ViewBindings.findChildViewById(rootView, id);
      if (editSignupEmail == null) {
        break missingId;
      }

      id = R.id.editSignupName;
      EditText editSignupName = ViewBindings.findChildViewById(rootView, id);
      if (editSignupName == null) {
        break missingId;
      }

      id = R.id.editSignupPassword;
      EditText editSignupPassword = ViewBindings.findChildViewById(rootView, id);
      if (editSignupPassword == null) {
        break missingId;
      }

      return new ActivitySignupBinding((ScrollView) rootView, btnSendCode, btnSignupConfirm,
          editSignupEmail, editSignupName, editSignupPassword);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
